// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Linky.Migrations
{
    [DbContext(typeof(LinkyDbContext))]
    [Migration("20230802090259_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DynamicLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AndroidMobileLink")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("AppleMobileLink")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("ShortIdentifier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("WebLink")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ShortIdentifier");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AndroidMobileLink = "https://play.google.com/store/apps/details?id=com.amazon.aws.console.mobile",
                            AppleMobileLink = "https://apps.apple.com/us/app/aws-console/id580990573",
                            ShortIdentifier = "aws",
                            WebLink = "https://aws.amazon.com/console/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
